# Generated by Django 5.1.4 on 2025-05-26 17:17

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_brance_name_bankdetails_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visalist',
            name='description',
        ),
        migrations.AddField(
            model_name='visalist',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
