# Generated by Django 5.2.1 on 2025-05-26 19:18

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_visalist_description_visalist_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagelist',
            name='description',
        ),
        migrations.AddField(
            model_name='packagelist',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
