# Generated by Django 5.2.1 on 2025-05-26 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_packagelist_description_packagelist_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagelist',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
