# Generated by Django 5.1.4 on 2025-09-04 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_our_services_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkstatus',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdf/'),
            preserve_default=False,
        ),
    ]
